apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              touch /data/db.sqlite3 &&
              chmod 777 /data/db.sqlite3 &&
              sleep infinity
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
